### ISSUE TITLE
Problem on install

### ISSUE THREAD

**Issue by jairjrpublicidade** [iutbay/yii2-kcfinder#1]
Hello,

During installation occurs the following problem:

iutbay/yii2-kcfinder 0.0.1 requires sunhater/kcfinder \* -> no matching package found.

Thank you for your attention.

Jair Jr.

**Comment by klevron** [comment]
Hello

KCFinder do not have stable release on packagist, you should adjust your stability settings :

``` json
"minimum-stability": "dev",
"prefer-stable": true,
```
